name: hls4ml
channels:
  - conda-forge
dependencies:
  - python=3.10.16
  - notebook=6.4
  - jupyter_contrib_nbextensions
  - jupyterhub
  - jupyterlab
  - jupyter-book
  - jsonschema-with-format-nongpl
  - pydot==1.4.2
  - graphviz==7.1.0
  - scikit-learn==1.2.2
  - tensorflow==2.15.0
  - tensorflow-datasets==4.8.3
  - webcolors
  - widgetsnbextension==3.6.0

#  - pip==23.0.1
  - pip:
      - pip install qkeras==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pip install hls4ml[profiling,optimization,sr,HGQ]==1.1.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pip install conifer==1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pip install pysr==0.16.3 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pip install xgboost==1.7.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pip install zstd -i https://pypi.tuna.tsinghua.edu.cn/simple
