name: hls4ml-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10.16
  - notebook=6.4
  - jupyter_contrib_nbextensions
  - jupyterhub
  - jupyter-book
  - jsonschema-with-format-nongpl
  - pydot==1.4.2
  - graphviz==7.1.0
  - scikit-learn==1.2.2
  - tensorflow==2.14.0
  - tensorflow-datasets==4.8.3
  - webcolors
  - widgetsnbextension==3.6.0
  - pip==23.0.1
  - pip:
      - hls4ml[profiling,optimization,sr,HGQ]==1.1.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - conifer==1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pysr==0.16.3 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - xgboost==1.7.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - zstd -i https://pypi.tuna.tsinghua.edu.cn/simple
